### ISSUE TITLE
command 'lando-ui.start' not found

### ISSUE THREAD

**Issue by Asterovim** [Jixabon/lando-ui#1]
Hello.
When clic "Lando start" i have this error :
`command 'lando-ui.start' not found`

I use lastest lando (v3.0.0-rrc.3) and docker 2.2.0.5 with windows 10.

I can start my lando without problem into powershell. The problem is only with this vscode extension.

Please help me.

**Comment by Jixabon** [comment]
There were some changes in Lando v3.0.0-rrc.1 and up that were causing some errors. I believe that v0.6.0 should fix this issue. Please test it and see if the error still occurs.

**Comment by Asterovim** [comment]
Thanks you it's fixed.
