### ISSUE TITLE
Extension not working after Lando upgrade

### ISSUE THREAD

**Issue by thegurf** [Jixabon/lando-ui#24]
Looks like a recent Lando update has caused this extension to stop functioning. Here's the error I'm seeing. 

![image](https://github.com/Jixabon/lando-ui/assets/11352596/8710e9f7-8786-43f9-a6bc-81414d94f052)

**Comment by thegurf** [comment]
Looks like I upgraded from v3.20.4 to v2.21.0-beta.8. Here's the other error I get on startup:

![image](https://github.com/Jixabon/lando-ui/assets/11352596/f02f0ebd-43cd-4215-8eaa-c257d9ebd524)

**Comment by Jixabon** [comment]
Looks like the checkVersion function is not including the beta version. I should have some time soon to revise this.

**Comment by Jixabon** [comment]
Issue should be fixed in v0.10.0. Let me know how it works!

**Comment by thegurf** [comment]
Thanks for the fix. Works great!
