### ISSUE TITLE
Unable to open URLs from the Lando Info panel

### ISSUE THREAD

**Issue by StevenGFX** [Jixabon/lando-ui#4]
I'm unable to open URLs from the Lando Info panel. I'm editing on Remote-WSL2: Ubuntu in Windows 10 if that helps.

![image](https://user-images.githubusercontent.com/6694844/79026847-bfe04400-7b4f-11ea-8a2c-a2da3202e288.png)

**Comment by Jixabon** [comment]
Just published v0.8.0 to start using the vscode api provided url open functionality. This may give more support across different operating systems. Please try it out and let me know if it works. If not we can continue to try.

**Comment by StevenGFX** [comment]
Thanks! That works for me. Good job on the project!

**Comment by Jixabon** [comment]
Awesome! If you don't mind leaving a [review](https://marketplace.visualstudio.com/items?itemName=jixabon.lando-ui) and maybe taking a little [survey](https://forms.gle/HH9wPoYor2rheUoS6) I put together. I'm kinda running out of ideas to expand on the utility.
