### ISSUE TITLE
Empty sql file on db-export with custom location

### ISSUE THREAD

**Issue by daltonrooney** [Jixabon/lando-ui#6]
When I export my database using the Lando default name and location, everything works as expected. But if I choose "Select and Name" I get an empty file. It doesn't seem to matter what location I save to.

Lando WordPress recipe with default database settings. Visual Studio v 1.42.1 on Mac OS Mojave.

**Comment by Jixabon** [comment]
Apologies for the delay. I just released v0.9.0 that should fix your issue. Please let me know if it persists. Thanks!

**Comment by daltonrooney** [comment]
Thanks, working as expected now. 👍
